### ISSUE TITLE
Black Screen in Retroarch

### ISSUE THREAD

**Issue by leonardo201800478** [ArcadeTV/msu-md-flintstones#1]
It does not work on Retroarch, after the Sega logo, a black screen only comes with the music playing until it locks up.
Version 1.0.

**Comment by ArcadeTV** [comment]
Please open the Menu in RetroArch after loading the game and go to "Core Information"
What is the exact version of your Core?

I suspect you are not using the latest core. (Cores downloaded via "update core" do not work)

**Comment by ArcadeTV** [comment]
![20210217_125019.jpg](https://user-images.githubusercontent.com/26868804/108200797-3d38f580-711f-11eb-8dc8-ce1ac76506f6.jpg)

**Comment by leonardo201800478** [comment]
![image](https://user-images.githubusercontent.com/67243028/108208760-3652b880-7108-11eb-97a9-94115d7163c5.png)

**Comment by leonardo201800478** [comment]
I had made some changes to the Info core to separate the colors, but even inserting the core without any changes, the game does not work, the ROM is correct and starts normally without the patch.

![image](https://user-images.githubusercontent.com/67243028/108209512-27203a80-7109-11eb-8185-a4b2b9217659.png)

**Comment by ArcadeTV** [comment]
Do you have a sega CD bios present in /systems folder?
Also make sure  your system is set to "NTSC-U" in options.

**Comment by leonardo201800478** [comment]
https://youtu.be/VgjUt2Hnhx0

**Comment by leonardo201800478** [comment]
Thanks, it worked now, the **System lockups** option has to be on, it was off.

**Comment by ArcadeTV** [comment]
Strange...
can you please do me a favor and try enter this in a cmd prompt or save it as `.bat` file and run it by doubleclick.
(You maybe need to adjust your path)
The `.bat` should sit in the same location as the .md and .cue
When using cmd prompt, please change dir to where your .md and .cue is.

´´´
C:\RetroArch\retroarch.exe -L "C:\RetroArch\cores\genesis_plus_gx_libretro.dll" -c "C:\RetroArch\retroarch.cfg" ".\Flintstones_MSU-MD_v1.0_ArcadeTV.md"
´´´

**Comment by ArcadeTV** [comment]
I had no idea about that option, I'll see if it has something to do with my asm.
Thanks!

**Comment by Agentmanbh** [comment]
Same issue in MED Pro.
Black screen after SEGA Logo speeched by Fred Flintstone.

**Comment by ArcadeTV** [comment]
I will have another look, sorry-

**Comment by ArcadeTV** [comment]
Please try v1.1
https://github.com/ArcadeTV/msu-md-flintstones/releases/latest

I think I figured it out...

**Comment by Agentmanbh** [comment]
Thanks!!
Ok, issue solved, but other appeared. No S.E., only musics can be heard.

**Comment by Flupper** [comment]
Sound effects are muted in v1.1 patch.

Thing is, I don't have any lockups in Retroarch 1.9.0+GX v1.7.4 58758ae with v1.0 (with fixed sfx bug).
I grabbed yesterdays source right after sfx fix was added from this repo and applied the asm patch with vasmm68k.
I made a bps patch out of this rom, works fine for me in RA.
https://www.mediafire.com/file/897l9osibj7ucq5/Flintstones%252C_The_%2528USA%2529_%2528Taito%2529_%2528MSU-MD%2529_%255Bv1.0_fixed_sfx_bug%255D.zip/file

**Comment by ArcadeTV** [comment]
@Flupper I think it only locks up in RA when Menu/Options/System Lockups is disabled.
So this is a workaround for RA but due to my bad coding it still locks up on Mega Everdrive Pro.
I know what caused it, it's how I bypassed the routine that plays sounds - as a one-man-show I didn't perform any extensive tests, my bad. Expect a v1.2 soon.

**Comment by ArcadeTV** [comment]
*Fingers crossed*
https://github.com/ArcadeTV/msu-md-flintstones/releases/latest
Grab v1.2
